version: 2.1
jobs:
  lint:
    docker:
      - image: nvuillam/npm-groovy-lint
    steps:
      - checkout

      - run: |
          npm-groovy-lint --fix --path "." --files "*.groovy"
          
      - run: |
          npm-groovy-lint --format --path "." --files "*.groovy"

workflows:
  version: 2
  "lint":
    jobs:
       - lint
